### ISSUE TITLE
HTML template to visualize MP stats

### ISSUE THREAD

**Issue by planemad** [folography/visavis#2]
Currently raw stats for MP is shown on hovering over a constituency like

<img width="934" alt="screenshot 2016-01-04 21 01 08" src="https://cloud.githubusercontent.com/assets/126868/12092989/680854fc-b326-11e5-8917-e5a6a24ab417.png">

@adityadipankar if you create and html+css prototype of how you want this to look, i can integrate into the sidebar for #1

**Comment by adityadipankar** [comment]
@planemad Cool, I'm on it!

**Comment by planemad** [comment]
https://github.com/folography/visavis/commit/a37b7104eb0e514d0b14ec5ee9cbec2aa1efe547 looks good.

**Next**
- [x] Integrate into the map

**Comment by planemad** [comment]
Integration done.
<img width="406" alt="screenshot 2016-01-05 01 16 29" src="https://cloud.githubusercontent.com/assets/126868/12098714/f6d21916-b349-11e5-8d50-14d564714fbb.png">
- [ ] @adityadipankar CSS improvement
