### ISSUE TITLE
Remove ractive

### ISSUE THREAD

**Issue by planemad** [folography/visavis#36]
For https://github.com/folography/netafilter/issues/34 the form template needs to be split into two. Also with the new data drive styling options in Mapbox GL, creating multiple layers for different colors is no longer necessary. The js can be greatly simplified by reducing the react implementation.

cc @shreyas-satish

**Comment by shreyas-satish** [comment]
We aren't using React. Think you mean [ractive](http://www.ractivejs.org/)?

**Comment by planemad** [comment]
yupyup

**Comment by planemad** [comment]
Partially done. Need to cleanup unused code after migrating to data based styling.
