### ISSUE TITLE
d3 scatter chart to show correlation between data fields

### ISSUE THREAD

**Issue by planemad** [folography/visavis#7]
Experiment creating a scatterplot using the [MP data](https://github.com/folography/visavis/blob/gh-pages/data/myneta-loksabha.csv) and [d3.scatter](http://nvd3.org/examples/scatter.html)

Possible fields for trials
- X axis - education
- Y axis - assets
- Marker color - party
- Marker size - criminal cases

**Comment by planemad** [comment]
Giving this a try

**Comment by planemad** [comment]
@priyankaborar @adityadipankar http://netafilter.in/chart.html

**Comment by adityadipankar** [comment]
Looking good!
